<?xml version="1.0" encoding="UTF-8"?>
<!--

    Copyright (c) 2025, 2026 Oracle and/or its affiliates.

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.

-->

<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
        xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>io.helidon.microprofile</groupId>
        <artifactId>helidon-microprofile-parent</artifactId>
        <version>5.0.0-SNAPSHOT</version>
        <relativePath>../parent/pom.xml</relativePath>
    </parent>
    <artifactId>helidon-microprofile-bom</artifactId>
    <packaging>pom</packaging>
    <name>Helidon MicroProfile BOM POM</name>

    <properties>
        <helidon.mp.version>5.0.0-SNAPSHOT</helidon.mp.version>
    </properties>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>io.helidon.microprofile</groupId>
                <artifactId>helidon-microprofile-all</artifactId>
                <type>pom</type>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.graphql</groupId>
                <artifactId>helidon-microprofile-graphql-server</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.grpc</groupId>
                <artifactId>helidon-microprofile-grpc-core</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.grpc</groupId>
                <artifactId>helidon-microprofile-grpc-server</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.grpc</groupId>
                <artifactId>helidon-microprofile-grpc-client</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.grpc</groupId>
                <artifactId>helidon-microprofile-grpc-tracing</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.config</groupId>
                <artifactId>helidon-microprofile-config-hocon</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.config</groupId>
                <artifactId>helidon-microprofile-config-yaml</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.bundles</groupId>
                <artifactId>helidon-microprofile-core</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.bundles</groupId>
                <artifactId>helidon-microprofile</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.security</groupId>
                <artifactId>helidon-microprofile-security</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile</groupId>
                <artifactId>helidon-microprofile-oidc</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.metrics</groupId>
                <artifactId>helidon-microprofile-metrics</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.weld</groupId>
                <artifactId>weld-core-impl</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.weld</groupId>
                <artifactId>weld-se-core</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.cdi</groupId>
                <artifactId>helidon-microprofile-cdi</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.config</groupId>
                <artifactId>helidon-microprofile-config</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.config</groupId>
                <artifactId>helidon-microprofile-config-core</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile</groupId>
                <artifactId>helidon-microprofile-fault-tolerance</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.health</groupId>
                <artifactId>helidon-microprofile-health</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.server</groupId>
                <artifactId>helidon-microprofile-server</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile</groupId>
                <artifactId>helidon-microprofile-access-log</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.websocket</groupId>
                <artifactId>helidon-microprofile-websocket</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.service-common</groupId>
                <artifactId>helidon-microprofile-service-common</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.jwt</groupId>
                <artifactId>helidon-microprofile-jwt-auth</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.tracing</groupId>
                <artifactId>helidon-microprofile-tracing</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.telemetry</groupId>
                <artifactId>helidon-microprofile-telemetry</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.jersey</groupId>
                <artifactId>helidon-jersey-client</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.jersey</groupId>
                <artifactId>helidon-jersey-common</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.jersey</groupId>
                <artifactId>helidon-jersey-connector</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.jersey</groupId>
                <artifactId>helidon-jersey-server</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.jersey</groupId>
                <artifactId>helidon-jersey-webserver</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.jersey</groupId>
                <artifactId>helidon-jersey-media-jsonp</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.jersey.tracing</groupId>
                <artifactId>helidon-jersey-tracing</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.jersey.tracing</groupId>
                <artifactId>helidon-jersey-tracing-client</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.rest-client</groupId>
                <artifactId>helidon-microprofile-rest-client</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.rest-client-metrics</groupId>
                <artifactId>helidon-microprofile-rest-client-metrics</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.reactive-streams</groupId>
                <artifactId>helidon-microprofile-reactive-streams</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.messaging</groupId>
                <artifactId>helidon-microprofile-messaging</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.messaging</groupId>
                <artifactId>helidon-microprofile-messaging-health</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.messaging</groupId>
                <artifactId>helidon-microprofile-messaging-metrics</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.messaging.connectors.aq</groupId>
                <artifactId>helidon-microprofile-messaging-connectors-aq</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.messaging.connectors</groupId>
                <artifactId>helidon-microprofile-messaging-connectors-jms-shim</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.messaging.connectors.jms</groupId>
                <artifactId>helidon-microprofile-messaging-connectors-jms</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.messaging.connectors.kafka</groupId>
                <artifactId>helidon-microprofile-messaging-connectors-kafka</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.messaging.connectors.mock</groupId>
                <artifactId>helidon-microprofile-messaging-connectors-mock</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.messaging.connectors.wls-jms</groupId>
                <artifactId>helidon-microprofile-messaging-connectors-wls-jms</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.scheduling</groupId>
                <artifactId>helidon-microprofile-scheduling</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.openapi</groupId>
                <artifactId>helidon-microprofile-openapi</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile</groupId>
                <artifactId>helidon-microprofile-cors</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.bean-validation</groupId>
                <artifactId>helidon-microprofile-bean-validation</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.testing</groupId>
                <artifactId>helidon-microprofile-testing</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.testing</groupId>
                <artifactId>helidon-microprofile-testing-junit5</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.testing</groupId>
                <artifactId>helidon-microprofile-testing-testng</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
            <dependency>
                <groupId>io.helidon.microprofile.testing</groupId>
                <artifactId>helidon-microprofile-testing-mocking</artifactId>
                <version>${helidon.mp.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
